### ISSUE TITLE
./gradlew installDist fails on Task :analyzer:compileKotlin

### ISSUE THREAD

**Issue by camillem** [heremaps/oss-review-toolkit#521]
Hi,

I can't compile the current master branch and get an error on Task :analyzer:compileKotlin

## Steps to reproduce the problem

I  have : 

-  installed  OpenJDK 8

>$ dpkg -l
ii  openjdk-8-jdk:amd64                           8u162-b12-1                                 amd64        OpenJDK Development Kit (JDK)

- Ensured  the `JAVA_HOME` environment variable is set.

> $ echo $JAVA_HOME 
/usr/lib/jvm/java-8-openjdk-amd64

- cloned the repo and launched the build: 

> git clone --recurse-submodules https://github.com/heremaps/oss-review-toolkit.git
cd oss-review-toolkit
./gradlew installDist

## Expected result

Successfull build

## Actual result
> FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':analyzer:compileKotlin'.

(More details below)

Did I miss somethig ?
Thanks,
Camille

> Task :analyzer:compileKotlin
file or directory '/home/camille/Devel/oss-review-toolkit/analyzer/src/main/java', not found
Build cache key for task ':analyzer:compileKotlin' is 4b3ff08342112e8deffd6c1f2d4a5f2b
Task ':analyzer:compileKotlin' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':analyzer:compileKotlin'.
file or directory '/home/camille/Devel/oss-review-toolkit/analyzer/src/main/java', not found
file or directory '/home/camille/Devel/oss-review-toolkit/analyzer/src/main/java', not found
Using Kotlin incremental compilation
Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0], reportSeverity=2, requestedCompilationResults=[0]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, workingDir=/home/camille/Devel/oss-review-toolkit/analyzer/build/kotlin/compileKotlin, customCacheVersionFileName='gradle-format-version.txt', customCacheVersion=4, resultDifferenceFile=/home/camille/Devel/oss-review-toolkit/analyzer/build/kotlin/compileKotlin/build-history.bin, friendDifferenceFile=null, usePreciseJavaTracking=truelocalStateDirs=[/home/camille/Devel/oss-review-toolkit/analyzer/build/classes/kotlin/main])

e: /home/camille/Devel/oss-review-toolkit/analyzer/src/main/kotlin/managers/Bundler.kt: (144, 13): No value passed for parameter 'definitionFilePath'

> Task :analyzer:compileKotlin FAILED
[KOTLIN] deleting /home/camille/Devel/oss-review-toolkit/analyzer/build/classes/kotlin/main on error
[KOTLIN] deleting /home/camille/Devel/oss-review-toolkit/analyzer/build/classes/kotlin/main on error
:analyzer:compileKotlin (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 5.363 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':analyzer:compileKotlin'.
> Compilation error. See log for more details

BUILD FAILED in 7s
17 actionable tasks: 1 executed, 16 up-to-date

**Comment by sschuberth** [comment]
This was a temporary issue due to a "semantic merge conflict" and has already been fixed by https://github.com/heremaps/oss-review-toolkit/pull/517/commits/657bc9cfc1557b74c10f8474a9bb681b59f589df. Please just pull and try again!

**Comment by camillem** [comment]
Thanks, it works indeed.
